### PR TITLE
Fix  #328: Fill opacity > 1 is processed incorrectly

### LINKED ISSUE #328: Fill opacity > 1 is processed incorrectly
test painting-fill-05-b-manual.svg
```
<rect x="200" y="20" width="60" height="60" fill-opacity="-100.0" fill="#0000FF" stroke="black"/>
    <rect x="230" y="50" width="60" height="60" fill-opacity="-10.0" fill="#0000FF" stroke="black"/>
    <rect x="260" y="80" width="60" height="60" fill-opacity="-0.1" fill="#0000FF" stroke="black"/>
    <rect x="290" y="110" width="60" height="60" fill-opacity="1.1" fill="#0000FF" stroke="black"/>
    <rect x="320" y="140" width="60" height="60" fill-opacity="10.0" fill="#0000FF" stroke="black"/>
    <rect x="350" y="170" width="60" height="60" fill-opacity="100.0" fill="#0000FF" stroke="black"/>
```

### PR DESCRIPTION
**Pull request by f3dm76**

### CODE REVIEW

File: Source/model/draw/Color.swift [hunk 1]
```diff
@@ -60,8 +60,9 @@ open class Color: Fill, Equatable {
         return Color( val: ( ( ( x | y ) | z ) | q ) )
     }
 
-    // GENERATED
+    // GENERATED NOT
     open class func rgba(r: Int, g: Int, b: Int, a: Double) -> Color {
+        let a = min(max(a, 0), 1)
```
Comment (ystrot) [inline Source/model/draw/Color.swift]: The place where opacity fixed looks little strange to me. Why do we fix it there, but not in the `rgbt` method? Why do we correct only `a`, but not `r`, `g`, `b` values?

From my point of view correcting all color values is overengineering and we need to assume that this method should be called with valid arguments. So I suggest to fix parser instead of a model.
